# Generated by Django 3.0 on 2019-12-19 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='machine',
            name='tape_json',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_json',
            field=models.TextField(default=''),
        ),
    ]
