# Generated by Django 3.0 on 2019-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0002_auto_20191219_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
