# Generated by Django 3.0 on 2019-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0003_auto_20191219_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
