# Generated by Django 3.0 on 2019-12-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0004_machine_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='id',
            new_name='uuid',
        ),
    ]
