# Generated by Django 3.0 on 2020-01-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0005_auto_20191229_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('D', 'Dfa'), ('N', 'Nfa'), ('P', 'Npda'), ('T', 'Turing')], default='D', max_length=1),
        ),
    ]
