# Generated by Django 3.0 on 2020-01-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0006_machine_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('D', 'Dfa'), ('N', 'Nfa'), ('P', 'Npda'), ('T', 'Turing')], max_length=1),
        ),
    ]
