# Generated by Django 3.0 on 2020-01-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0007_auto_20200109_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('D', 'DFA'), ('N', 'NFA'), ('P', 'NPDA'), ('T', 'Turing')], max_length=1),
        ),
    ]
