# Generated by Django 3.0 on 2020-02-11 21:59

from django.db import migrations

def fix_json(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Machine = apps.get_model('machinestore', 'Machine')
    for machine in Machine.objects.all():
        machine.machine_json = machine.machine_json.replace("\'", "\"")
        machine.save()
        print("fixed machine")


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0009_auto_20200109_0117'),
    ]

    operations = [
        migrations.RunPython(fix_json)
    ]
