# Generated by Django 3.0 on 2020-02-11 22:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinestore', '0012_auto_20200211_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='tape_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
