# Generated by Django 2.0.5 on 2018-06-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlatex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latexexpr',
            name='svg_file',
        ),
        migrations.AddField(
            model_name='latexexpr',
            name='svg_data',
            field=models.TextField(default=''),
        ),
    ]
