# Generated by Django 2.0.5 on 2018-05-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaTeXExpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('accesses', models.BigIntegerField(verbose_name='number of accesses')),
                ('svg_file', models.FileField(upload_to='latex_cache')),
            ],
        ),
    ]
